apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: portal-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8sportal-client
subjects:
- kind: ServiceAccount
  namespace: default
  name: {{ include "k8sportal.serviceAccountName" . }}